/**:
  ros__parameters:
    # MoveIt uses this configuration for controller management

    moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

    moveit_simple_controller_manager:
      controller_names:
        - gp70l_joint_trajectory_controller

      gp70l_joint_trajectory_controller:
        action_ns: follow_joint_trajectory
        type: FollowJointTrajectory
        joints:
          - gp_joint_1
          - gp_joint_2
          - gp_joint_3
          - gp_joint_4
          - gp_joint_5
          - gp_joint_6
